name: Bump Dependencies

on:
  repository_dispatch:
    types: [bump-dependencies]

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: spinnaker/bumpdeps@master
      with:
        ref: ${{ github.event.client_payload.ref }}
        key: monikerVersion
        repositories: kork
        mavenRepositoryUrl: https://dl.bintray.com/spinnaker/spinnaker
        groupId: com.netflix.spinnaker.moniker
        artifactId: moniker
      env:
        GITHUB_OAUTH: ${{ secrets.SPINNAKER_GITHUB_TOKEN }}
